Auto switch use iam-role/irsa when aws_access_key, aws_secret_key is leaved null
opensourceelectrolux/aws-cost-exporter pull request #13
Opened 2024-05-15 03:22 UTC by sfarcana

I add auto switch use iam-role, irsa (run on EKS) when aws_access_key, aws_secret_key is leaved null
And an example for deployment use irsa on EKS

2024-05-15 12:47 UTC, gluckzhang commented
Hi @sfarcana, many thanks for making contributions to the project! It's great that you provide both the code and the documentation. I will review it later and get back to you :)

2024-05-16 06:48 UTC, jneumann90 commented
Successfully tested via IAM-User-Credentials and IAM-Instance-Role :)

One just has to take care of the [order](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) in which boto3 looks for credentials, ("Instance metadata service on an Amazon EC2 instance that has an IAM role configured." -> is last the option checked).

So if you have exported the aws-credentials via the offical ENV-Vars:
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID
AWS_SESSION_TOKEN

The role of the instance and the credentials configured via paremters "aws_access_key" and "aws_access_secret" will be ignored, and the above mentioned credentials will be used instead.

2024-05-17 08:24 UTC, gluckzhang requested changes

2024-05-17 08:24 UTC, gluckzhang commented on app/exporter.py
> +    def get_aws_account_session(self, account_id):
actually, this should become the default behavior since it follows boto3's order of looking for credentials. The previous approach can be called something like `get_aws_account_session_via_iam_user`. What do you think? It is just about a better naming :)

2024-05-17 08:26 UTC, gluckzhang commented
Thanks @jneumann90 for testing it and also clarifying the credential orders!
@sfarcana the code looks nice to me. I don't see any major issue, just a question about naming. Regarding @jneumann90 's comment above, could you please add this piece of clarification about boto3's behavior to the doc? Thanks in advance!

2024-05-17 15:45 UTC, sfarcana commented
many thank @jneumann90 and @gluckzhang review and test this MR, I will check and update boto3's behavior clearly,  and function's name, I'll check and change it in next commit 👍

2024-05-20 06:45 UTC, sfarcana commented on app/exporter.py
> +    def get_aws_account_session(self, account_id):
I changed to  `get_aws_account_session_via_iam_user` in [this commit](https://github.com/opensourceelectrolux/aws-cost-exporter/pull/13/commits/e9db3a005592d7827de1cdfd65f1a4a1fb4ba6d1) , a better name @gluckzhang

2024-05-20 09:02 UTC, gluckzhang requested changes

2024-05-20 09:02 UTC, gluckzhang commented on app/exporter.py
> +    def get_aws_account_session_default(self, account_id):
As this method reads IAM user credentials (`aws_access_key` and `aws_secret_accss_key`), it should be named as `get_aws_account_session_via_iam_user`.

2024-05-20 09:02 UTC, gluckzhang commented on app/exporter.py
> +    def get_aws_account_session_via_iam_user(self, account_id):
In this method, `boto3` automatically locates the credentials and assumes the role (no parameters other than `"sts"` are specified) so it should be named as `get_aws_account_session_default`.

2024-05-20 09:02 UTC, gluckzhang commented on app/exporter.py
> +            aws_credentials = self.get_aws_account_session_via_iam_user(aws_account["Publisher"])
If no credentials are given, use the default behavior:
```
        if self.aws_access_key == "" and self.aws_access_secret == "":
            aws_credentials = self.get_aws_account_session_default(aws_account["Publisher"])
        else:
            aws_credentials = self.get_aws_account_session_via_iam_user(aws_account["Publisher"])
```

2024-05-20 09:51 UTC, sfarcana commented on app/exporter.py
> +            aws_credentials = self.get_aws_account_session_via_iam_user(aws_account["Publisher"])
hi @gluckzhang I make some changes in [this commit](https://github.com/opensourceelectrolux/aws-cost-exporter/pull/13/commits/16390abe7f0b7ba184c441cff5a9a36e16e11e02), you can review it again

2024-05-21 01:52 UTC, sfarcana commented
hi @gluckzhang, I [commit](https://github.com/opensourceelectrolux/aws-cost-exporter/pull/13/commits/d5029ebd7cdfc09e7408f65a57406d889f99e90d) about boto3's behavior in exporter 😃, waiting for your review 🚀

2024-05-21 07:19 UTC, gluckzhang approved these changes

2024-05-21 07:23 UTC, merged

2024-05-21 07:24 UTC, gluckzhang commented
It looks great. Thanks you @sfarcana for the contribution!

2024-05-23 10:51 UTC, jneumann90 commented
Great, thank you guys! <3